"""MedGemma narrative writer.

Builds a free-text clinical narrative from a list of structured Findings.
Two backends:

  - mock (default): deterministic template, no network. Used in tests
    and in any deployment where MEDGEMMA_BACKEND is unset.
  - hf: POST to a Hugging Face Inference Endpoint hosting MedGemma.
    Text-only input — pixel data is never sent.

Every NarrativeResult is wrapped in a RESEARCH USE ONLY disclaimer.
On any failure (missing config, HTTP error, malformed response) the
narrator returns NarrativeResult(text=None, error=...) so the pipeline
can keep generating the report without the narrative.
"""
from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass
from typing import Any, Literal

import httpx

from app.core.config import settings
from app.db.models.finding import Finding as FindingRow
from app.db.models.study import Study

log = logging.getLogger(__name__)

RESEARCH_DISCLAIMER = (
    "RESEARCH USE ONLY — NOT FOR DIAGNOSIS. "
    "Generated by AI; requires licensed radiologist review before clinical use."
)

PROMPT_SYSTEM = (
    "You are a radiology AI assistant. Your output is for RESEARCH ONLY — "
    "NOT for diagnosis or treatment. Summarize the AI findings below in a "
    "brief clinical narrative (3–6 sentences). Do not invent findings not "
    "listed. Do not provide treatment recommendations. Do not include "
    "patient identifiers."
)


@dataclass
class NarrativeResult:
    text: str | None
    backend: str
    model_id: str
    prompt_token_estimate: int
    error: str | None = None


def _findings_block(findings: list[FindingRow]) -> str:
    if not findings:
        return "(no AI findings produced)"
    lines = []
    for f in findings:
        parts = [f"- {f.label}"]
        if f.body_part:
            parts.append(f"site={f.body_part}")
        if f.confidence is not None:
            parts.append(f"confidence={f.confidence:.2f}")
        if f.icd10_suggestion:
            parts.append(f"ICD-10={f.icd10_suggestion}")
        if f.model_name:
            parts.append(f"model={f.model_name} v{f.model_version}")
        lines.append("  ".join(parts))
    return "\n".join(lines)


def _build_prompt(study: Study, findings: list[FindingRow]) -> str:
    return (
        f"{PROMPT_SYSTEM}\n\n"
        f"Study context:\n"
        f"- Modality: {study.modality}\n"
        f"- Body part: {study.body_part}\n"
        f"- Description: {study.description or '(none)'}\n\n"
        f"AI findings:\n{_findings_block(findings)}\n\n"
        f"Write the narrative now. Begin with: 'AI narrative (research only):'."
    )


class MedGemmaNarrator:
    """Narrative writer with pluggable backend."""

    name = "MedGemmaNarrator"

    def __init__(
        self,
        *,
        backend: Literal["mock", "hf"] = "mock",
        model_id: str = "google/medgemma-4b-it",
        hf_endpoint_url: str = "",
        hf_token: str = "",
        max_new_tokens: int = 512,
        timeout_seconds: float = 20.0,
    ) -> None:
        self.backend = backend
        self.model_id = model_id
        self.hf_endpoint_url = hf_endpoint_url
        self.hf_token = hf_token
        self.max_new_tokens = max_new_tokens
        self.timeout_seconds = timeout_seconds

    async def narrate(
        self, *, study: Study, findings: list[FindingRow]
    ) -> NarrativeResult:
        prompt = _build_prompt(study, findings)
        token_estimate = max(1, len(prompt) // 4)
        if self.backend == "mock":
            return self._mock(study, findings, token_estimate)
        if self.backend == "hf":
            return await self._hf(prompt, token_estimate)
        return NarrativeResult(
            text=None,
            backend=self.backend,
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
            error=f"unknown backend: {self.backend}",
        )

    def narrate_sync(
        self, *, study: Study, findings: list[FindingRow]
    ) -> NarrativeResult:
        return asyncio.run(self.narrate(study=study, findings=findings))

    def _mock(
        self,
        study: Study,
        findings: list[FindingRow],
        token_estimate: int,
    ) -> NarrativeResult:
        if not findings:
            text = (
                "AI narrative (research only): No AI findings were produced for "
                f"this {study.modality} {study.body_part} study. The radiologist "
                "should still complete an independent read.\n\n"
                f"{RESEARCH_DISCLAIMER}"
            )
            return NarrativeResult(
                text=text,
                backend="mock",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
            )

        bullets = []
        for f in findings:
            conf = (
                f" (model confidence {f.confidence:.2f})"
                if f.confidence is not None
                else ""
            )
            icd = f" → suggested ICD-10 {f.icd10_suggestion}" if f.icd10_suggestion else ""
            bullets.append(f"{f.label}{conf}{icd}")
        joined = "; ".join(bullets)
        text = (
            "AI narrative (research only): "
            f"On this {study.modality} {study.body_part} study, the AI flagged "
            f"the following candidate findings: {joined}. These are unverified "
            "AI candidates and require radiologist confirmation, correlation with "
            "prior imaging, and clinical context before any interpretation.\n\n"
            f"{RESEARCH_DISCLAIMER}"
        )
        return NarrativeResult(
            text=text,
            backend="mock",
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
        )

    async def _hf(self, prompt: str, token_estimate: int) -> NarrativeResult:
        if not self.hf_endpoint_url:
            return NarrativeResult(
                text=None,
                backend="hf",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
                error="endpoint not configured",
            )
        headers = {
            "Authorization": f"Bearer {self.hf_token}" if self.hf_token else "",
            "Content-Type": "application/json",
        }
        # Gemma chat template wrap. The HF Inference Endpoint accepts the
        # raw text-generation shape; we leave higher-level chat templating
        # to the endpoint's tokenizer config.
        body: dict[str, Any] = {
            "inputs": prompt,
            "parameters": {
                "max_new_tokens": self.max_new_tokens,
                "temperature": 0.2,
                "return_full_text": False,
            },
        }
        try:
            async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
                resp = await client.post(
                    self.hf_endpoint_url, headers=headers, json=body
                )
                resp.raise_for_status()
                data = resp.json()
        except Exception as exc:  # noqa: BLE001
            log.warning("medgemma hf call failed: %s", exc)
            return NarrativeResult(
                text=None,
                backend="hf",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
                error=str(exc)[:500],
            )

        generated = _extract_generated_text(data)
        if not generated:
            return NarrativeResult(
                text=None,
                backend="hf",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
                error=f"unrecognized response shape: {type(data).__name__}",
            )

        text = generated.strip()
        if RESEARCH_DISCLAIMER not in text:
            text = f"{text}\n\n{RESEARCH_DISCLAIMER}"
        return NarrativeResult(
            text=text,
            backend="hf",
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
        )


def _extract_generated_text(data: Any) -> str | None:
    """HF Inference Endpoints return either a list or a dict depending on
    the deployed task. Accept both shapes."""
    if isinstance(data, list) and data:
        first = data[0]
        if isinstance(first, dict) and "generated_text" in first:
            return str(first["generated_text"])
    if isinstance(data, dict):
        if "generated_text" in data:
            return str(data["generated_text"])
        # chat-completion-style fallback
        choices = data.get("choices")
        if isinstance(choices, list) and choices:
            msg = choices[0].get("message") or {}
            content = msg.get("content")
            if isinstance(content, str):
                return content
    return None


def build_narrator() -> MedGemmaNarrator:
    """Construct a narrator from settings. Mock backend if unset."""
    backend = (settings.medgemma_backend or "mock").lower()
    if backend not in ("mock", "hf"):
        log.warning("unknown MEDGEMMA_BACKEND=%s, falling back to mock", backend)
        backend = "mock"
    return MedGemmaNarrator(
        backend=backend,  # type: ignore[arg-type]
        model_id=settings.medgemma_model_id,
        hf_endpoint_url=settings.medgemma_hf_endpoint_url,
        hf_token=settings.medgemma_hf_token,
        max_new_tokens=settings.medgemma_max_new_tokens,
        timeout_seconds=float(settings.medgemma_timeout_seconds),
    )
