"""MedGemma narrative writer.

Builds a free-text clinical narrative from a list of structured Findings.
Two backends:

  - mock (default): deterministic template, no network. Used in tests
    and in any deployment where MEDGEMMA_BACKEND is unset.
  - hf: POST to a Hugging Face Inference Endpoint hosting MedGemma.
    Text-only input — pixel data is never sent.

Every NarrativeResult is wrapped in a RESEARCH USE ONLY disclaimer.
On any failure (missing config, HTTP error, malformed response) the
narrator returns NarrativeResult(text=None, error=...) so the pipeline
can keep generating the report without the narrative.
"""
from __future__ import annotations

import asyncio
import logging
import threading
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from typing import Any, Coroutine, Literal, TypeVar

import httpx

from app.core.config import settings

_T = TypeVar("_T")
_BG_EXECUTOR = ThreadPoolExecutor(max_workers=2, thread_name_prefix="medgemma-sync")


def _run_async(coro: Coroutine[Any, Any, _T]) -> _T:
    """Run an awaitable from sync code, regardless of whether the caller is
    inside a running event loop.

    The old `asyncio.run(coro)` raised RuntimeError when called from a thread
    already running an event loop (e.g. the seed scripts that `await
    ingest_synthetic_studies()` → `generate_report()` → `narrate_sync()`).
    This helper detects that case and runs the coroutine on a background
    thread that owns its own loop.
    """
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)
    # Already inside a loop → can't nest asyncio.run; offload.
    return _BG_EXECUTOR.submit(lambda: asyncio.run(coro)).result()
from app.db.models.finding import Finding as FindingRow
from app.db.models.study import Study

log = logging.getLogger(__name__)

RESEARCH_DISCLAIMER = (
    "RESEARCH USE ONLY — NOT FOR DIAGNOSIS. "
    "Generated by AI; requires licensed radiologist review before clinical use."
)

PROMPT_SYSTEM = (
    "You are a radiology AI assistant. Your output is for RESEARCH ONLY — "
    "NOT for diagnosis or treatment. Summarize the AI findings below in a "
    "brief clinical narrative (3–6 sentences). Do not invent findings not "
    "listed. Do not provide treatment recommendations. Do not include "
    "patient identifiers."
)

DEFAULT_HF_PATH = "/v1/chat/completions"

PROMPT_COMPARE_SYSTEM = (
    "You are a radiology AI assistant generating a CHANGE REPORT between "
    "two imaging studies. Output for RESEARCH ONLY — NOT for diagnosis or "
    "treatment. Compare the AI findings between the two timepoints. State "
    "what is new, what has resolved, and what appears stable. Do not "
    "invent findings not present in either list. Do not provide treatment "
    "recommendations. Keep the report concise (3–6 sentences)."
)


@dataclass
class NarrativeResult:
    text: str | None
    backend: str
    model_id: str
    prompt_token_estimate: int
    error: str | None = None


def _findings_block(findings: list[FindingRow]) -> str:
    if not findings:
        return "(no AI findings produced)"
    lines = []
    for f in findings:
        parts = [f"- {f.label}"]
        if f.body_part:
            parts.append(f"site={f.body_part}")
        if f.confidence is not None:
            parts.append(f"confidence={f.confidence:.2f}")
        if f.icd10_suggestion:
            parts.append(f"ICD-10={f.icd10_suggestion}")
        rads = (f.geometry or {}).get("rads") if getattr(f, "geometry", None) else None
        if rads:
            parts.append(f"{rads['scheme']}={rads['code']}")
        if f.model_name:
            parts.append(f"model={f.model_name} v{f.model_version}")
        lines.append("  ".join(parts))
    return "\n".join(lines)


def _build_user_message(study: Study, findings: list[FindingRow]) -> str:
    """User-turn content for chat models. The system prompt goes in a
    separate message; legacy text-generation endpoints concat the two."""
    return (
        f"Study context:\n"
        f"- Modality: {study.modality}\n"
        f"- Body part: {study.body_part}\n"
        f"- Description: {study.description or '(none)'}\n\n"
        f"AI findings:\n{_findings_block(findings)}\n\n"
        f"Write the narrative now. Begin with: 'AI narrative (research only):'."
    )


def _build_prompt(study: Study, findings: list[FindingRow]) -> str:
    return f"{PROMPT_SYSTEM}\n\n{_build_user_message(study, findings)}"


def _build_compare_message(
    baseline: Study,
    follow_up: Study,
    baseline_findings: list[FindingRow],
    follow_up_findings: list[FindingRow],
) -> str:
    return (
        f"BASELINE study ({baseline.study_date}):\n"
        f"- Modality: {baseline.modality}\n"
        f"- Body part: {baseline.body_part}\n"
        f"- Description: {baseline.description or '(none)'}\n"
        f"- Findings:\n{_findings_block(baseline_findings)}\n\n"
        f"FOLLOW-UP study ({follow_up.study_date}):\n"
        f"- Modality: {follow_up.modality}\n"
        f"- Body part: {follow_up.body_part}\n"
        f"- Description: {follow_up.description or '(none)'}\n"
        f"- Findings:\n{_findings_block(follow_up_findings)}\n\n"
        "Write the change report now. Begin with: "
        "'AI change report (research only):'."
    )


class MedGemmaNarrator:
    """Narrative writer with pluggable backend."""

    name = "MedGemmaNarrator"

    def __init__(
        self,
        *,
        backend: Literal["mock", "hf"] = "mock",
        model_id: str = "google/medgemma-27b-text-it",
        hf_endpoint_url: str = "",
        hf_token: str = "",
        max_new_tokens: int = 512,
        timeout_seconds: float = 20.0,
    ) -> None:
        self.backend = backend
        self.model_id = model_id
        self.hf_endpoint_url = hf_endpoint_url
        self.hf_token = hf_token
        self.max_new_tokens = max_new_tokens
        self.timeout_seconds = timeout_seconds

    async def narrate(
        self, *, study: Study, findings: list[FindingRow]
    ) -> NarrativeResult:
        user_msg = _build_user_message(study, findings)
        token_estimate = max(1, (len(PROMPT_SYSTEM) + len(user_msg)) // 4)
        if self.backend == "mock":
            return self._mock(study, findings, token_estimate)
        if self.backend == "hf":
            return await self._hf(user_msg, token_estimate)
        return NarrativeResult(
            text=None,
            backend=self.backend,
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
            error=f"unknown backend: {self.backend}",
        )

    def narrate_sync(
        self, *, study: Study, findings: list[FindingRow]
    ) -> NarrativeResult:
        return _run_async(self.narrate(study=study, findings=findings))

    async def compare_studies(
        self,
        *,
        baseline: Study,
        follow_up: Study,
        baseline_findings: list[FindingRow],
        follow_up_findings: list[FindingRow],
    ) -> NarrativeResult:
        """Generate a free-text change report between two timepoints."""
        user_msg = _build_compare_message(
            baseline, follow_up, baseline_findings, follow_up_findings
        )
        token_estimate = max(1, (len(PROMPT_COMPARE_SYSTEM) + len(user_msg)) // 4)
        if self.backend == "mock":
            return self._mock_compare(
                baseline, follow_up, baseline_findings, follow_up_findings, token_estimate
            )
        if self.backend == "hf":
            return await self._hf(
                user_msg, token_estimate, system=PROMPT_COMPARE_SYSTEM
            )
        return NarrativeResult(
            text=None,
            backend=self.backend,
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
            error=f"unknown backend: {self.backend}",
        )

    def compare_studies_sync(
        self,
        *,
        baseline: Study,
        follow_up: Study,
        baseline_findings: list[FindingRow],
        follow_up_findings: list[FindingRow],
    ) -> NarrativeResult:
        return _run_async(
            self.compare_studies(
                baseline=baseline,
                follow_up=follow_up,
                baseline_findings=baseline_findings,
                follow_up_findings=follow_up_findings,
            )
        )

    def _mock_compare(
        self,
        baseline: Study,
        follow_up: Study,
        baseline_findings: list[FindingRow],
        follow_up_findings: list[FindingRow],
        token_estimate: int,
    ) -> NarrativeResult:
        baseline_labels = {f.label for f in baseline_findings}
        follow_labels = {f.label for f in follow_up_findings}
        new = follow_labels - baseline_labels
        resolved = baseline_labels - follow_labels
        stable = baseline_labels & follow_labels
        parts = []
        if new:
            parts.append(f"New: {', '.join(sorted(new))}.")
        if resolved:
            parts.append(f"Resolved: {', '.join(sorted(resolved))}.")
        if stable:
            parts.append(f"Stable: {', '.join(sorted(stable))}.")
        if not parts:
            parts.append("No AI findings on either timepoint.")
        text = (
            f"AI change report (research only): Comparing {baseline.modality} "
            f"{baseline.body_part} on {baseline.study_date} vs. "
            f"{follow_up.modality} {follow_up.body_part} on "
            f"{follow_up.study_date}. " + " ".join(parts) + f"\n\n{RESEARCH_DISCLAIMER}"
        )
        return NarrativeResult(
            text=text,
            backend="mock",
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
        )

    def _mock(
        self,
        study: Study,
        findings: list[FindingRow],
        token_estimate: int,
    ) -> NarrativeResult:
        if not findings:
            text = (
                "AI narrative (research only): No AI findings were produced for "
                f"this {study.modality} {study.body_part} study. The radiologist "
                "should still complete an independent read.\n\n"
                f"{RESEARCH_DISCLAIMER}"
            )
            return NarrativeResult(
                text=text,
                backend="mock",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
            )

        bullets = []
        for f in findings:
            conf = (
                f" (model confidence {f.confidence:.2f})"
                if f.confidence is not None
                else ""
            )
            icd = f" → suggested ICD-10 {f.icd10_suggestion}" if f.icd10_suggestion else ""
            bullets.append(f"{f.label}{conf}{icd}")
        joined = "; ".join(bullets)
        text = (
            "AI narrative (research only): "
            f"On this {study.modality} {study.body_part} study, the AI flagged "
            f"the following candidate findings: {joined}. These are unverified "
            "AI candidates and require radiologist confirmation, correlation with "
            "prior imaging, and clinical context before any interpretation.\n\n"
            f"{RESEARCH_DISCLAIMER}"
        )
        return NarrativeResult(
            text=text,
            backend="mock",
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
        )

    async def _hf(
        self,
        user_msg: str,
        token_estimate: int,
        *,
        system: str = PROMPT_SYSTEM,
    ) -> NarrativeResult:
        if not self.hf_endpoint_url:
            return NarrativeResult(
                text=None,
                backend="hf",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
                error="endpoint not configured",
            )
        headers = {
            "Authorization": f"Bearer {self.hf_token}" if self.hf_token else "",
            "Content-Type": "application/json",
        }
        url = self.hf_endpoint_url.rstrip("/") + DEFAULT_HF_PATH
        # vLLM / TGI OpenAI-compatible chat completions. The server's
        # tokenizer applies the model's chat template, so we don't have
        # to know whether it's Gemma-2 or Gemma-3 format.
        body: dict[str, Any] = {
            "model": self.model_id,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": user_msg},
            ],
            "max_tokens": self.max_new_tokens,
            "temperature": 0.2,
        }
        try:
            async with httpx.AsyncClient(timeout=self.timeout_seconds) as client:
                resp = await client.post(url, headers=headers, json=body)
                resp.raise_for_status()
                data = resp.json()
        except Exception as exc:  # noqa: BLE001
            log.warning("medgemma hf call failed: %s", exc)
            return NarrativeResult(
                text=None,
                backend="hf",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
                error=str(exc)[:500],
            )

        generated = _extract_generated_text(data)
        if not generated:
            return NarrativeResult(
                text=None,
                backend="hf",
                model_id=self.model_id,
                prompt_token_estimate=token_estimate,
                error=f"unrecognized response shape: {type(data).__name__}",
            )

        text = generated.strip()
        if RESEARCH_DISCLAIMER not in text:
            text = f"{text}\n\n{RESEARCH_DISCLAIMER}"
        return NarrativeResult(
            text=text,
            backend="hf",
            model_id=self.model_id,
            prompt_token_estimate=token_estimate,
        )


def _extract_generated_text(data: Any) -> str | None:
    """HF Inference Endpoints return either a list or a dict depending on
    the deployed task. Accept both shapes."""
    if isinstance(data, list) and data:
        first = data[0]
        if isinstance(first, dict) and "generated_text" in first:
            return str(first["generated_text"])
    if isinstance(data, dict):
        if "generated_text" in data:
            return str(data["generated_text"])
        # chat-completion-style fallback
        choices = data.get("choices")
        if isinstance(choices, list) and choices:
            msg = choices[0].get("message") or {}
            content = msg.get("content")
            if isinstance(content, str):
                return content
    return None


def build_narrator() -> MedGemmaNarrator:
    """Construct a narrator from settings. Mock backend if unset."""
    backend = (settings.medgemma_backend or "mock").lower()
    if backend not in ("mock", "hf"):
        log.warning("unknown MEDGEMMA_BACKEND=%s, falling back to mock", backend)
        backend = "mock"
    return MedGemmaNarrator(
        backend=backend,  # type: ignore[arg-type]
        model_id=settings.medgemma_model_id,
        hf_endpoint_url=settings.medgemma_hf_endpoint_url,
        hf_token=settings.medgemma_hf_token,
        max_new_tokens=settings.medgemma_max_new_tokens,
        timeout_seconds=float(settings.medgemma_timeout_seconds),
    )
